Adding predef datasets and slurm job updates

diff --git a/slurm-job b/slurm-job
--- a/slurm-job
+++ b/slurm-job
@@ -46,19 +46,41 @@ function wait_for_dag
     return 0
 }
 
+function cancel_search
+{
+    if [ "x$CONDOR_JOB_ID" != "x" ]; then
+        echo "Canceling HTCondor job $CONDOR_JOB_ID ..."
+    	condor_rm $CONDOR_JOB_ID
+    fi
+    sleep 3s
+}
 
-if [ ! -n "$1" -o ! -n "$2" ]; then
-        echo "Usage: ./`basename $0` <file with list of SRA IDs> <reference file>"
-        echo "Example: ./`basename $0` sra_ids.txt crassphage.fna"
-        exit $E_BADARGS
-fi
+
+echo
+echo
+ls -l
+echo
+echo
 
 TOP_DIR=`dirname $0`
 TOP_DIR=`cd $TOP_DIR && pwd`
 
+# this script assumes the current working directory has files
+# uploaded by the portal: reference and optionally sra_ids.txt
+
+# handle the case where users select to use a pre-defined id file
+if [ ! -e sra_ids.txt ]; then
+    if [ -e /srv/sra-search/pre-defined/$2 ]; then
+        cp /srv/sra-search/pre-defined/$2 sra_ids.txt
+    else
+        my_log "$2 is not a valid pre-defined id file"
+        exit 1
+    fi
+fi
+
 # define WORK_DIR so that submit-dag does not create a new one
 export WORK_DIR=`pwd`
-$TOP_DIR/submit-dag $1 $2 2>&1 | tee submit.log
+$TOP_DIR/submit-dag sra_ids.txt reference 2>&1 | tee submit.log
 
 # now wait for the dag to complete
 CONDOR_JOB_ID=`cat submit.log | grep "submitted to cluster" | perl -p -i -e 's/.*cluster ([0-9]+).*/$1/'`
@@ -67,6 +89,9 @@ if [ "X$CONDOR_JOB_ID" = "X" ]; then
     exit 1
 fi
 my_log "Monitoring HTCondor job id $CONDOR_JOB_ID"
+
+# clean up if the job is canceled
+trap "cancel_search" SIGINT SIGTERM
 
 # also send email about it
 if [ "X$USER" = "Xgw" ]; then
@@ -115,6 +140,8 @@ fi
 if [ "X$USER" = "Xgw" ]; then
     cat $MAIL_BODY_FILE | mailx -s "$MAIL_SUBJECT" "$ADMIN_EMAILS"
 fi
+
+CONDOR_JOB_ID=""
 
 exit $EXIT_CODE
 
