Grouping of searches. Handle missing SRAs.

diff --git a/slurm-job b/slurm-job
--- a/slurm-job
+++ b/slurm-job
@@ -2,13 +2,39 @@
 
 set -e
 
-function is_job_running
+ADMIN_EMAILS="raedwards@gmail.com, rynge@isi.edu, eroma_a@yahoo.com"
+
+function my_log
 {
-    STATUS=`condor_q $1 -nob -af JobStatus 2>/dev/null`
-    if [ "x$STATUS" = "x" ]; then
-        return 1
-     fi
-     return 0
+    echo "INFO:  $@"
+}
+
+
+function wait_for_dag
+{
+    JOB_ID=$1
+
+    ERROR_COUNT=0
+    DONE=0
+    while [ $DONE = 0 ]; do
+        STATUS=`condor_q $JOB_ID -nob -af JobStatus 2>/dev/null`
+
+        # see http://pages.cs.wisc.edu/~adesmet/status.html
+        if [ "X$STATUS" = "X5" ]; then
+            DONE=1
+        elif [ "X$STATUS" = "X2" ]; then
+            ERROR_COUNT=0
+        elif [ "X$STATUS" = "X" ]; then
+            # can't find dag - try for a while, and then give up
+            ERROR_COUNT=$(($ERROR_COUNT + 1))
+            if [ $ERROR_COUNT -gt 10 ]; then
+                return 0
+            fi
+        fi
+        sleep 10s
+    done
+
+    return 0
 }
 
 
@@ -27,10 +53,52 @@ $TOP_DIR/submit-dag $1 $2 2>&1 | tee submit.log
 
 # now wait for the dag to complete
 CONDOR_JOB_ID=`cat submit.log | grep "submitted to cluster" | perl -p -i -e 's/.*cluster ([0-9]+).*/$1/'`
-echo "Monitoring HTCondor job id $CONDOR_JOB_ID"
+my_log "Monitoring HTCondor job id $CONDOR_JOB_ID"
 
-while is_job_running $CONDOR_JOB_ID; do
-    sleep 10s
-done
+# also send email about it
+cat <<EOF | mailx -s "SRA Gateway: New search submitted - $SLURM_SUBMIT_DIR" "$ADMIN_EMAILS"
+Started a new SRA Gateway search:
+
+SLURM_SUBMIT_DIR = $SLURM_SUBMIT_DIR
+HTCondor DAG ID = $CONDOR_JOB_ID
+EOF
+
+wait_for_dag $CONDOR_JOB_ID
+
+if [ -e report.txt ]; then
+    echo
+    cat report.txt
+fi
+
+MAIL_SUBJECT="SRA Gateway search: successful - $SLURM_SUBMIT_DIR"
+MAIL_BODY_FILE=body.txt
+EXIT_CODE=0
+cat <<EOF >$MAIL_BODY_FILE
+SLURM_SUBMIT_DIR = $SLURM_SUBMIT_DIR
+HTCondor DAG ID = $CONDOR_JOB_ID
+
+EOF
+if (cat sra.dag.dagman.out | tail -n 1 | grep "STATUS 0") >/dev/null 2>&1; then
+    echo
+    echo "Search finished successfully!"
+    echo
+    cat report.txt >>$MAIL_BODY_FILE
+else
+    echo
+    echo "The search finished with errors. Here are the last 100 lines of the log:"
+    echo
+    if [ -e sra.dag.dagman.out ]; then
+        tail -n 100 sra.dag.dagman.out
+    fi
+    MAIL_SUBJECT="SRA Gateway search: failed - $SLURM_SUBMIT_DIR"
+    echo "\n\nThe search finished with errors. Here are the last 100 lines of the log:\n" >>$MAIL_BODY_FILE
+    tail -n 100 sra.dag.dagman.out >>$MAIL_BODY_FILE
+    EXIT_CODE=1
+fi
+
+# send admin email
+cat $MAIL_BODY_FILE | mailx -s "$MAIL_SUBJECT" "$ADMIN_EMAILS"
+
+exit $EXIT_CODE
 
 
